version: '3.3'
services:
  grafana-admin:
    image:  grafana/grafana:latest
    container_name: grafana-admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - 3001:3000
  crawler:
    container_name: serp-crawler
    build: ./crawler
    volumes:
      - /data:/home/app/mount
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb
  grafana:
    build:
      context: ./grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
    external: true
  influxdb-volume:
    external: true