version: '3.2'
services:
  crawler:
    container_name: serp-crawler
    build: ./crawler
    volumes:
      - /data:/home/app/mount
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_PROXY_AUTO_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true
    ports:
      - 3000:3000
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - /data:/var/lib/influxdb