version: '3.2'
services:
  crawler:
    container_name: serp-crawler
    build: ./crawler
    volumes:
      - /data:/home/app/mount
  server:
    container_name: serp-server
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - /data:/home/app/mount
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_PROXY_AUTO_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml