version: '3.3'
services:
  crawler:
    container_name: serp-crawler
    build: ./crawler
    volumes:
      - /data:/home/app/mount
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    volumes:
      - type: volume
        source: grafana-volume
        target: /var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
  grafana-admin:
    build:
      context: ./grafan-admina
    container_name: grafana-admin
    volumes:
      - type: volume
        source: grafana-volume
        target: /var/lib/grafana
    ports:
      - 3001:3000
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_USER: $INFLUXDB_USERNAME
      INFLUXDB_ADMIN_PASSWORD: $INFLUXDB_PASSWORD
volumes:
  grafana-volume: