version: '3.2'
services:
  crawler:
    container_name: serp-crawler
    build: ./crawler
    volumes:
      - /data:/home/app/mount
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: $GRAFANA_ADMIN_USER
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_ADMIN_PASSWORD

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      INFLUXDB_USERNAME: $INFLUXDB_USERNAME
      INFLUXDB_PASSWORD: $INFLUXDB_PASSWORD
volumes:
  grafana-storage:
    external: true
  influxdb-volume:
    external: true