{
 "title": "RankTank",
 "description": "Operational dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "category",
    "label": "Category",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.tagValues(\n  bucket: \"serp_rank\",\n  tag: \"category_name\",\n  predicate: (r) => true,\n  start: -30d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "SERP Rank Volatility Index",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"serp_rank\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category_name\"] == \"${category}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Crawlers",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Running Instances",
      "alignmentPeriod": "+3600s",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudfunctions.googleapis.com/function/active_instances",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "ranktank",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Cached SERPs (Minute)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_COUNT",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "firestore.googleapis.com/api/request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "ranktank",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Uncached SERPs (Minute)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_COUNT",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "firestore.googleapis.com/document/write_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "ranktank",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "SERP Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Execution Time",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/execution_times",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "ranktank",
      "unit": "ns",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "SERP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Execution Count",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/execution_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "ranktank",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Loadbalancer Requests (Minute)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Loadbalancer Requests",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "ranktank",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Egress Traffic (Minute)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Egress Count",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vm_flow/egress_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "ranktank",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}